# Streamlit Secrets Configuration
# Store sensitive configuration here

[app]
debug_mode = false
show_confidence = true
auto_save_scans = true

# Dual Portal Authentication
staff_password = "admin123"  # Change this to a secure password for production